/**
 *
 * @returns A unique numeric ID as a string.
 * This ID is generated by combining the current timestamp and a random number.
 *
 */

export function generateNumericId(): string {
  const timestamp = BigInt(Date.now());
  const random = BigInt(Math.floor(Math.random() * 1e9));
  const id = timestamp * BigInt(1_000_000_000) + random;
  return id.toString();
}
